# Generated by Django 3.0.8 on 2020-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mars_weather_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_no', models.CharField(max_length=3, verbose_name='sol_no')),
                ('date', models.DateField()),
                ('season', models.CharField(max_length=20, verbose_name='season')),
                ('air_temp_avg', models.CharField(max_length=10, verbose_name='air_temp_avg')),
                ('air_temp_max', models.CharField(max_length=10, verbose_name='air_temp_max')),
                ('air_temp_min', models.CharField(max_length=10, verbose_name='air_temp_min')),
                ('wind_speed_avg', models.CharField(max_length=10, verbose_name='wind_speed_avg')),
                ('pressure_reading_avg', models.CharField(max_length=10, verbose_name='pressure_reading_avg')),
                ('wind_direction', models.CharField(max_length=10, verbose_name='wind_direction')),
                ('wind_angle', models.CharField(max_length=10, verbose_name='wind_angle')),
            ],
        ),
    ]
