# Generated by Django 3.0.8 on 2020-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mars_weather_data',
            name='air_temp_avg',
            field=models.FloatField(verbose_name='air_temp_avg'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='air_temp_max',
            field=models.FloatField(verbose_name='air_temp_max'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='air_temp_min',
            field=models.FloatField(verbose_name='air_temp_min'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='pressure_reading_avg',
            field=models.FloatField(verbose_name='pressure_reading_avg'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='sol_no',
            field=models.IntegerField(verbose_name='sol_no'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='wind_angle',
            field=models.FloatField(verbose_name='wind_angle'),
        ),
        migrations.AlterField(
            model_name='mars_weather_data',
            name='wind_speed_avg',
            field=models.FloatField(verbose_name='wind_speed_avg'),
        ),
    ]
