# Generated by Django 3.0.8 on 2020-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200730_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mars_weather_data',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
