# Generated by Django 3.0.8 on 2020-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_mars_weather_data_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mars_weather_data',
            old_name='date',
            new_name='sol_date',
        ),
        migrations.AddField(
            model_name='mars_weather_data',
            name='api_req_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
