# Generated by Django 3.0.8 on 2020-07-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200730_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mars_weather_data',
            old_name='api_req_date',
            new_name='api_req_date_utc',
        ),
    ]
